#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

# Build main radlib first
wmake $targetType .

# Build rcslw_data binaries
wmake $targetType data/rcslw_data

cd data/rcslw_data
export DYLD_LIBRARY_PATH="$FOAM_LD_LIBRARY_PATH"
./writebin.x
cd ../..

# Build examples
wmake $targetType examples/simple_interface
wmake $targetType examples/ex_B3
wmake $targetType examples/ex_S1
wmake $targetType examples/ex_S2
wmake $targetType examples/ex_S3
wmake $targetType examples/ex_S4
wmake $targetType examples/ex_S5
wmake $targetType examples/ex_Sb1

#------------------------------------------------------------------------------